add review popup component
tezkerek/minniebooks pull request #33
Opened 2023-04-29 18:14 UTC by Qmpzlawasd

2023-04-29 20:28 UTC, tezkerek requested changes

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +function Stars({ ratingMax, stars, setStars }: StarsProps) {
This can be an independent component in its own file.

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +  setStars: Function;
Naming: `maxRating`, `rating`, `onRatingChange`

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +  setStars: Function;
Add an actual signature to `onRatingChange`, like `(rating: number) => void`.

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +function Stars({ ratingMax, stars, setStars }: StarsProps) {
Naming: `RatingSelector`?

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +function WriteReviewPopup(): JSX.Element {
Naming: `ReviewEditor`? We'll probably use it to edit reviews as well.

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +        <TextareaAutosize
Make the initial textarea larger.

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +  const [textReview, setTextReview] = useState<string>("");
Naming is backwards: this is the review's text, not the text's review.

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +  const [stars, setStars] = useState<number>(0);
Naming: use `rating` for consistency with the Review entity.

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +            console.log(textReview, stars);
If you add a `onDone: (review: Review) => void` prop, you can make this an independent component too.

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> -const reviews = [{ id: 1, rating: 4, text: "Pretty good book", authorUsername: 'the_critic' }, { id: 2, rating: 2, text: "GarBAGE", authorUsername: 'hater' }]
Don't change unrelated lines.

2023-04-29 20:28 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +const mockBook = {
Here and below: don't change unrelated lines.

2023-05-01 09:47 UTC, Qmpzlawasd commented on frontend/src/pages/books/[id].tsx
> +            console.log(textReview, stars);
> If you add a `onDone: (review: Review) => void` prop, you can make this an independent component too.
Could you be more specific?

2023-05-01 11:53 UTC, tezkerek commented on frontend/src/pages/books/[id].tsx
> +            console.log(textReview, stars);
When it's finished editing, `ReviewEditor` should return the updated/created review to its parent via the `onDone` callback. And now `ReviewEditor` should be in its own file.

2023-05-03 10:28 UTC, tezkerek approved these changes

2023-05-03 10:29 UTC, merged